### ISSUE TITLE
Permissions issue with packages when using Jamf Sync

### ISSUE THREAD

**Issue by jcon526** [jamf/JamfSync#18] opened 2024-07-03 20:08 UTC
I saw that one of the posted issues already mentioned permissions problems, so apologies for repeating it, but it doesn't seem to be fixed:

I recently downloaded Jamf Sync v1.3.2 (I just found out today, 7-3-2024, that Jamf Admin was no longer supported).   

I'm able to use the app to sync from our institution's jamfcloud instance to two different Mac minis (used as jamf package distribution points) just fine ... but when any of the newly-synced packages arrives, it triggers errors in the app (I can post those errors later if you need them).  Despite the errors, the packages still copy fine.

However, when I go to the mac minis themselves, I check the permissions of the new packages, and they display the "jamfwrite" account being correctly set to "Read & Write", BUT "Everyone" is set to "No Access".  

Because of this, when I run a jamf command to run a policy using the new package, it errors out trying to read the package from one of the distribution point mac minis because it has no access to it, and fails over to the jamfcloud instance.

I'm able to get around this by running terminal commands on each mac mini to fix the permissions of the entire "Packages" folder and its contents.  But I wanted to post this so you were aware.

Again, apologies, as I'll be out of the office for about a week or so and won't be able to reply quickly. -jc

**Comment by TimCraftA52** [comment] 2024-07-11 16:47
I'll jump on this one since my original post was closed as fixed. This sounds very similar to my original issue.

In my case my read only AND read/write users ACL's are missing.

How it should be -
perry-1# ls -ldea Slack_4.38.121*
-rwxrwxrwx + 1 A52\jamfadmin wheel 192950416 May 13 15:57 Slack_4.38.121.pkg
OWNER: user:A52\jamfadmin
GROUP: group:wheel
CONTROL:sacl_auto_inherited
0: user:A52\jamfclient allow file_gen_read
1: user:A52\jamfadmin allow file_gen_all

How it is now, user ACL's missing-
-rwxrwxrwx + 1 A52\jamfadmin wheel 192950416 May 14 09:19 Slack_4.38.121_v1.pkg
OWNER: user:A52\jamfadmin
GROUP: group:wheel
CONTROL:dacl_auto_inherited,sacl_auto_inherited
0: SID:S-1-5-88-3-384 deny

Posix is fine, the ACL's do not come over or maybe are removed after the copy?

I can confirm my NAS is functioning properly with ACL's being inherited to files being copied, it looks like after the copy you may be clearing these inherited ACL's after its done?

**Comment by jcon526** [comment] 2024-07-16 17:20
Yes, indeed; the permissions aren't getting inherited properly when the files are copied.  I am using the latest version of Jamf Sync v1.3.2, so if it's fixed, I do wonder if the issue is that the mac minis I'm using as distribution points need to be at a certain macOS to function properly.  The Jamf Sync app requires macOS Sonoma, but both mac minis are still at Mojave.  It's no great issue to upgrade to the latest macOS they can go, but I was leaving them alone because of the "if it ain't broke, don't fix it" philosophy and since they've worked fine with Jamf Admin.  I'll sit on this until I hear more on this thread; it's not a terribly big deal to run Terminal commands to fix the permissions every time I sync, at least for now.

**Comment by willsmithcc** [comment] 2024-07-17 17:55
This is happening to me too on Sonoma.

**Comment by dev-yeet** [comment] 2024-08-05 21:00
im getting the same thing on my end. i basically have to go and make sure i do a "chmod +r *" on that directory to get my packages to work again.

**Comment by chriskeavey-kkl** [comment] 2024-09-02 14:26
Just adding my voice to this issue. I also still have to chmod the folder. Any updates on the progress of this issue?

**Comment by ctarbox** [comment] 2024-10-07 18:28
I am experience the exact same permission issues as jcon526 describes. I have updated Jamf Sync to version 1.3.2 with no changes. My mac mini distribution points are running Ventura 13.7. I am also going directly to the distribution point and manually updating the packages permissions.

**Comment by willsmithcc** [comment] 2024-10-21 19:11
Same here. Version 1.3.3 released today has the same issue. Sure wish they'd friggin' at least acknowledge the issue...

**Comment by HarryStrandJamf** [comment] 2024-10-21 21:37
Sorry folks, when I was going through all these issues to see what I could fix with 1.3.3, somehow I missed this one. @willsmithcc - Acknowledged. What kind of distribution point are you guys synchronizing from and to when this happens?

**Comment by willsmithcc** [comment] 2024-10-21 22:00
Thanks @HarryStrandJamf - Sorry for the snark, it's been a long day. Syncing from a JCDS to an HTTPS/SMB folder share on a Mac.

**Comment by ctarbox** [comment] 2024-10-22 11:29
I have the same distribution point setup. JCDS to HTTPS/SMB share folder on Mac Minis. I have four individual distribution points feeding different subnets on our campus.

Cheryl E Tarbox
Macintosh System Administrator & Senior Tech Support Specialist
Adobe License Administrator
Jamf Certified Technician
***@***.***
LN G101 • 607-777-2870
Zoom: https://binghamton.zoom.us/j/3125597839
My Booking Calendar <https://calendar.app.google/hNPGDKRwVeEGZ8vt5>
￼

**Comment by HarryStrandJamf** [comment] 2024-10-22 13:16
@willsmithcc No apology necessary...my bad for missing this one. Also, it was Monday! Thanks for the info. Is anyone see this with anything other than JCDS to SMB?

**Comment by guillaumegete** [comment] 2024-10-22 16:21
Same issue for me, sync from JCDS to local Mac mini sharing datas through SMB, errors as everyone is forbidden.

**Comment by dev-yeet** [comment] 2024-10-22 17:47
just throwing in a data point that we're syncing to a Mac hosted SMB share as well.

**Comment by HarryStrandJamf** [comment] 2024-10-25 15:31
We believe this issue is fixed with version 1.4.0 so I'm closing this one. Please let us know if you continue to have issues though.

**Closed by HarryStrandJamf** 2024-10-25 15:31 UTC

**Comment by nfawad227** [comment] 2024-12-03 18:34
having this issue my end 

24/12/03 09:27:50-ERROR: Failed to load the USNO DGN JAMF (Jamf) distribution point: mountingFailed
