### ISSUE TITLE
Cannot delete item from JDCS/Filenames with unexpected chars

### ISSUE THREAD

**Issue by macnotes** [jamf/JamfSync#6] opened 2024-05-09 21:30 UTC
Sync version: 1.3

Reproduce: 
1. Name a package "FileNameTest~!@#$%^&*()_`1234567890-=[]\{}|";'<>?,:..pkg"
2. Upload package to JDCS
3. Attempt to delete package from JDCS

Expected behavior: 
Package is deleted. 

Current behavior: 
```24/05/09 17:17:35-ERROR: Failed to deleted FileNameTest~!@#$%^&*()_`1234567890-=[]\{}|";'<>?,:..pkg from JCDS (o): dataRequestFailed(statusCode: 400, message: Optional("<!doctype html><html lang=\"en\"><head><title>HTTP Status 400 – Bad Request</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>"))```

**Comment by macnotes** [comment] 2024-05-09 21:38
Side note... it's totally cosmetic but on classic API call error logging, if I see the response starts with "doctype html", I usually strip out the <style></style> section for readability. I don't know that it's worth the effort here.

**Comment by macnotes** [comment] 2024-05-09 21:50
Might want to put a pin in this while I test more... issue might be me. 

I deleted all packages in the Jamf Pro GUI. 

This file still shows as being in my JDCS in Sync. 

<img width="1133" alt="image" src="https://github.com/jamf/JamfSync/assets/25835285/72e7682f-1201-4b8c-b76a-97bc2ef37384">

**Comment by HarryStrandJamf** [comment] 2024-06-17 16:23
I wasn't able to include the colon in the filename since that's a limitation of macOS. But I was able to reproduce the problem without that. However, it appears that this may be a limitation of the Jamf Pro API because I get the same failure if I try to delete it via the swagger docs (jssUrl/api).

**Comment by HarryStrandJamf** [comment] 2024-06-17 16:29
Closing this for now (see comment above)

**Closed by HarryStrandJamf** 2024-06-17 16:29 UTC
