### ISSUE TITLE
Can't upload ZIP files

### ISSUE THREAD

**Issue by damienf55** [jamf/JamfSync#21] opened 2024-07-10 10:29 UTC
Hi Jamf developer team

I can't upload zip file with jamf sync. In Jamf Admin, I could upload zip file.
When I put zip file into network volume, it disappears ....

Thanks

**Comment by Adem-UMN** [comment] 2024-07-10 15:44
I've noticed that .zip and .dmg files are no longer showing on the file list, even if they exist on the server. The file may have been uploaded but just being displayed.

**Comment by HarryStrandJamf** [comment] 2024-07-11 14:07
What kind of zip files did you need to upload? Jamf Admin allowed uploading of older non-flat packages, and it would convert those to zip files. I believe the original extension was still in the file name and ".zip" was appended. Jamf Sync will only show zip files with ".pkg.zip" and ".mpkg.zip" extensions. Jamf Admin would also allow you to upload .app files and it would zip them, however, that was in order to upload macOS installers, which is no longer relevant after macOS 10.13 I believe.

**Comment by damienf55** [comment] 2024-07-15 08:15
examples : pkg as disrectory : jamf admin compress it in zip file. Trend AV need a file near pkg to install computer in managment app. Zip file in a rule are "hidden" to be use with a script

Thank-you

**Comment by HarryStrandJamf** [comment] 2024-07-15 14:18
Jamf Sync will compress pkg's and mpkg's that are directories into a zip file with a .pkg.zip or .mpkg.zip extension. As long as zip files have one of those two extensions, they should show up in the list. I tested it with the latest version and it's working that way.

**Comment by HarryStrandJamf** [comment] 2024-08-15 14:29
Closing this ticket since I wasn't able to reproduce the issue and I haven't gotten further information. The last comment mentioned a script...if you have a specific example, feel free to reopen it with additional information.

**Closed by HarryStrandJamf** 2024-08-15 14:29 UTC
